---
title: "Data loading"
author: "Martin"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    code_folding: hide

---

```{r setup, echo = FALSE}
suppressPackageStartupMessages(library(here))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(peekbankr))

# Seed for random number generation
set.seed(43)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed, cache = TRUE, 
                      message=FALSE, warning=FALSE, error=FALSE)
FIRST_TIME <- TRUE
repo_name <- "workshop_2024_dev"
```


## Get data

```{r, eval=FIRST_TIME}
con <- connect_to_peekbank(db_version = "workshop_2024_dev")
all_aoi_timepoints <- get_aoi_timepoints(connection = con, rle=FALSE)

# reload connection in case it is stale
con <- connect_to_peekbank(db_version = "workshop_2024_dev")
all_stimuli <- collect(get_stimuli(connection = con))
all_administrations <- collect(get_administrations(connection = con))
all_subjects <- collect(get_subjects(connection = con))
all_trial_types <- collect(get_trial_types(connection = con))
all_trials <- collect(get_trials(connection = con))
```

Now do the joins. 

```{r, eval=FIRST_TIME}
aoi_data_joined <- all_aoi_timepoints |>
  right_join(all_administrations) |>
  right_join(all_subjects) |>
  right_join(all_trials) |>
  right_join(all_trial_types) |>
  mutate(stimulus_id = target_id) |>
  left_join(all_stimuli) |>
  select(dataset_name, subject_id, administration_id, trial_id, trial_order, dataset_id, 
         stimulus_id, distractor_id, t_norm, age, aoi, english_stimulus_label, 
         stimulus_novelty, target_side, vanilla_trial,coding_method) %>%
  rename(target_label = english_stimulus_label, 
         target_id = stimulus_id) %>%
  left_join(all_stimuli %>%
              select(stimulus_id, dataset_id, 
                     stimulus_novelty, english_stimulus_label) %>%
              rename(distractor_id = stimulus_id, 
                     distractor_novelty = stimulus_novelty,
                     distractor_label = english_stimulus_label))

save(aoi_data_joined, file= here("cached_intermediates","1_aoi_data_joined.Rds"))
```

Check on number of datasets. 

```{r}
load(here("cached_intermediates", "1_aoi_data_joined.Rds"))
length(unique(aoi_data_joined$dataset_name))
unique(aoi_data_joined$dataset_name)
```

Create a trial data

```{r}
d_trial <- aoi_data_joined |>
  select(dataset_name, subject_id, administration_id, trial_id, trial_order,
         dataset_id, target_id, t_norm, age, aoi, target_label, distractor_label, target_side) |>
  mutate(correct = ifelse(aoi == "target", 1, 
                          ifelse(aoi == "distractor", 0, NA)))

d_trial <- d_trial |>
  filter(t_norm >= -4000, t_norm <= 4000)

save(d_trial, file = here("cached_intermediates","1_d_trial.Rds"))
```



