---
title: "longitudinal_switching_analysis"
output: html_document
date: '2024-08-27'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(data.table)
library(ggplot2)
library(dplyr)
library(tidyr)

source("../peekbank-shiny/helpers/rt_helper.R")
```

## Developmental changes in gaze switching between target and distractor

See notes here:
<https://docs.google.com/document/d/1ySCNzheHPT261JNX44VyonfwkapzK212TEMS3DFS4xA/edit>

```{r loading_data}
# Loading peekbank data into a variable called aoi_data_joined
load(here("cached_intermediates/1_aoi_data_joined.Rds"))
```

```{r selecting_datasets_for_analysis}

# select adams_marchman dataset (in the future this will be all hand-coded datasets)
hand_coded_df <- aoi_data_joined %>%
  filter(dataset_name == "adams_marchman_2018")
```

```{r tagging_switches}
rle_data <- hand_coded_df %>%
  filter(any(t_norm == 0)) %>% # only pass data after 0
  group_by(dataset_name, dataset_id,subject_id, administration_id, trial_id) %>%
  reframe(min_tnorm=min(t_norm),
          max_tnorm=max(t_norm),
    lengths = rle(aoi)$lengths, 
            values = rle(aoi)$values) 

rle_data_with_times <- rle_data %>%
  group_by(dataset_name, dataset_id,subject_id, administration_id, trial_id) %>%
  mutate(
    total_trial_length=max_tnorm-min_tnorm,
    cumulative_length_start = lag(cumsum(lengths),default=0),
    cumulative_length_end = cumsum(lengths),
    t_start = min_tnorm+cumulative_length_start*25,
    t_end = min_tnorm+(cumulative_length_end-1)*25,
    trial_stage = ifelse(t_end < 0, "pre-critical",
                         ifelse(t_end < max_tnorm/2, "first half",
                                "second half")))

#join back in relevant data
rle_data_with_times <-
  left_join(rle_data_with_times,
            aoi_data_joined %>%
              select(subject_id, administration_id, trial_id,
                     age, dataset_name,
                     vanilla_trial,target_label, target_side,
                     stimulus_novelty, distractor_novelty,distractor_label) %>%
              distinct())

rle_data_with_times <-
  rle_data_with_times %>%
  group_by(subject_id, trial_id, administration_id, trial_stage) %>%
  mutate(
    switch_num=length(values)-1,
    switch_num_per_trial_len = switch_num/total_trial_length,
    length_ms=lengths*25
  )

```

```{r}

# create summary df for number of switches
rle_data_with_times_switchnum_summary =
  rle_data_with_times %>%
  # group data by subject, administration session, age, and trial stage
  group_by(administration_id, subject_id, age, trial_stage) %>%
  # get mean and SDs for number of switches, standardized by trial length
  summarise(mean = mean(switch_num_per_trial_len),
            sd = sd(switch_num_per_trial_len))

# create summary df for length of switches
rle_data_with_times_switchlength_summary =
  rle_data_with_times %>%
  # group data by subject, administration session, age, and trial stage
  group_by(administration_id, subject_id, age, trial_stage) %>%
  # get mean and SDs for LENGTH of switches
  summarise(mean = mean(length_ms),
            sd = sd(length_ms))

```

```{r}

# Plot age distribution
hist(rle_data_with_times$age)

```

```{r}

# number of switches by age and trial_stage
ggplot(data = rle_data_with_times_switchnum_summary,
       aes(x = age,
           y = mean,
           fill = trial_stage)) +
  geom_point(alpha = .05,
             aes(color = factor(trial_stage))) +
  geom_smooth() +
  scale_x_continuous(limits = c(6, 84),
                     breaks = seq(6, 84, 6)) +
  scale_y_continuous(limits = c(0, .007),
                   breaks = seq(0, .007, .001)) +
  labs(y = "Mean # of Switches (Std. by Trial Length)",
     x = "Age in months",
     fill = "Trial Stage",
     color = element_blank()) +
  theme_minimal()

```

```{r}

# length of switches by age and trial_stage
ggplot(data = rle_data_with_times_switchlength_summary,
       aes(x = age,
           y = mean,
           fill = trial_stage)) +
  geom_point(alpha = .05,
             aes(color = factor(trial_stage))) +
  geom_smooth() +
  scale_x_continuous(limits = c(6, 84),
                     breaks = seq(6, 84, 6)) +
  scale_y_continuous(limits = c(0, 11000),
                     breaks = seq(0, 11000, 2750)) +
  labs(y = "Mean Length of Switches",
       x = "Age in months",
       fill = "Trial Stage",
       color = element_blank()) +
  theme_minimal()

```

------------------------------------------------------------------------------------------

MARTINS CODE

Average switches per administration

```{r}
# admin_rle_data_with_times <- rle_data_with_times %>%
#   group_by(dataset_name, dataset_id,subject_id, administration_id,age,
#            vanilla_trial,target_label, target_side,
#            stimulus_novelty, distractor_novelty,distractor_label) %>%
#   summarize(
#     avg_switch_num = mean(switch_num,na.rm=T),
#     avg_switch_norm = mean(switch_num_per_trial_len),
#     avg_length=mean(length_ms),
#     sd_length=sd(length_ms)
#   )
```

```{r}
# ggplot(admin_rle_data_with_times,aes(age,avg_switch_num)) +
#   geom_point(alpha=0.1)+
#   geom_smooth(method="lm")#+
#   #facet_wrap(~dataset_name)
# 
# ggplot(admin_rle_data_with_times,aes(age,avg_length)) +
#   geom_point(alpha=0.1)+
#   geom_smooth(method="loess",se=F)#+
#   #facet_wrap(~dataset_name)

```
