---
title: "longitudinal_switching_analysis"
output: html_document
date: '2024-08-27'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(data.table)
library(ggplot2)
library(dplyr)
library(tidyr)


source("../peekbank-shiny/helpers/rt_helper.R")
```

## Developmental changes in gaze switching between target and distractor

See notes here: https://docs.google.com/document/d/1ySCNzheHPT261JNX44VyonfwkapzK212TEMS3DFS4xA/edit



```{r loading_data}
# Loading peekbank data into a variable called aoi_data_joined
load(here("cached_intermediates/1_aoi_data_joined.Rds"))
```

```{r selecting_datasets}
# select adams_marchman dataset (in the future this will be all hand-coded datasets)
hand_coded_df <- aoi_data_joined %>%
  filter(dataset_name == "adams_marchman_2018")


# Here we are coding each of the 4 administrations per subject
# as administrations 1-4. There are 2 administrations
# per age (e.g., 2 at 16 months, 2 at 19 months)
# In practice, this gets the ordering correctly
# in the sense that the first two administrations are 1-2
# and the second 2 are 2-3. But it may be worth checking
#  the actual order of the administrations at the same
# age
hand_coded_df = hand_coded_df %>%
  group_by(subject_id) %>%
  mutate(
    new_admin_id = paste0(dense_rank(administration_id))
  ) %>%
  ungroup() 

```


```{r tagging_gaze_switches}

# Here I am counting missing or other as the same thing, we may
# want to change that in the future

#hand_coded_df <- hand_coded_df %>%
#  mutate(recoded_aoi = recode(aoi, 
#                      "missing" = "other_missing", 
#                      "other" = "other_missing"))

# for each administration, we're computing the total number of
# switches. I defined this as a different gaze target on the next frame,
# which includes the following switches:
# target -> distractor, [missing, or other]
# distractor -> target, [missing or other]
# [missing or other] -> target, distractor

# we may want to change our definition of switch in the future
# e.g., we may include a threshold for amount of time spent in the region

#hand_coded_df <- hand_coded_df %>%
#  group_by(trial_id) %>%
#  mutate(
#    switches = if_else(aoi != lag(aoi, default = first(aoi)), 1, 0),
#    switches = if_else(row_number() == 1, 0, switches)  # Set first row's switch to 0
#  ) %>%
#  ungroup()

rle_data <- hand_coded_df %>%
  filter(any(t_norm == 0), # must have data at 0
         t_norm >= 0) %>% # only pass data after 0
  group_by(dataset_name, dataset_id,subject_id, administration_id, trial_id) %>%
  reframe(min_tnorm=min(t_norm),
          max_tnorm=max(t_norm),
    lengths = rle(aoi)$lengths, 
            values = rle(aoi)$values) 

rle_data_with_times <- rle_data %>%
  group_by(dataset_name, dataset_id,subject_id, administration_id, trial_id) %>%
  mutate(
    total_trial_length=max_tnorm-min_tnorm,
    cumulative_length_start = lag(cumsum(lengths),default=0),
    cumulative_length_end = cumsum(lengths),
    t_start = min_tnorm+cumulative_length_start*25,
    t_end = min_tnorm+(cumulative_length_end-1)*25,
  ) %>%
  #total_switches
  mutate(
    switch_num=length(values)-1,
    switch_num_per_trial_len = switch_num/total_trial_length,
    length_ms=lengths*25
  )

#join back in relevant data
rle_data_with_times <- left_join(rle_data_with_times,aoi_data_joined %>%
                   select(subject_id, administration_id, trial_id, 
                          age, dataset_name,
                          vanilla_trial,target_label, target_side,
                          stimulus_novelty, distractor_novelty,distractor_label) %>%
                   distinct())

```

```{r computing_number_of_switches_per_administration}
# We are getting the total number of gaze switches for each administration, for each participant


# Compute number of switches per trial

#trial_switches <- hand_coded_df %>%
  # selecting all columns except tnorm, aoi, recoded aoi and switches - there's a more efficient way to do this
  # but this works for now
  #group_by(dataset_name, subject_id, administration_id, trial_id, trial_order, dataset_id, target_id,
  #        distractor_id, age, target_label, stimulus_novelty, target_side, vanilla_trial, distractor_novelty,    #            distractor_label, new_admin_id) %>%
  #summarize(switch_num = sum(switches)) %>%
  #ungroup()


# Calculate the average number of switches per administration and subject
#avg_gaze_switches_by_administraton_by_subj <- trial_switches %>%
#  group_by(subject_id,new_admin_id, age) %>%
#  summarize(avg_switches = mean(switch_num)) %>%
#  ungroup()


# Create the plot
#ggplot(avg_gaze_switches_by_administraton_by_subj, aes(x = new_admin_id, y = avg_switches, group = subject_id, #color = factor(subject_id))) +
#  geom_line() +  # Line for each subject
#  geom_point() + # Points for each subject
#  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "black") +  # Smooth line across all subjects
#  labs(x = "Administration Number", y = "Average Switches", color = "Subject ID") +
#  theme_minimal()

#ggplot(avg_gaze_switches_by_administraton_by_subj, aes(x = age, y = avg_switches, group = subject_id, color = factor(subject_id))) +
#  geom_line() +  # Line for each subject
#  geom_point() + # Points for each subject
#  geom_smooth(aes(group = 1), method = "loess", se = FALSE, color = "black") +  # Smooth line across all subjects
#  labs(x = "Administration Number", y = "Average Switches", color = "Subject ID") +
#  theme_minimal()


```